// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.linux:
        return defaultOption;
      case TargetPlatform.windows:
        return defaultOption;
      case TargetPlatform.fuchsia:
        return defaultOption;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6uNW17e_lZZKXnCmpQyuay9qZfvGjy5w',
    appId: '1:599045906068:web:c683c36807fc687e121e81',
    messagingSenderId: '599045906068',
    projectId: 'resume-builder-6ad54',
    authDomain: 'resume-builder-6ad54.firebaseapp.com',
    storageBucket: 'resume-builder-6ad54.appspot.com',
    measurementId: 'G-3EQTKS7F4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_B4Gw9Z3RUlt9T4smA4LdOZEg55iu5nI',
    appId: '1:599045906068:android:e4e61e79115a0ea6121e81',
    messagingSenderId: '599045906068',
    projectId: 'resume-builder-6ad54',
    storageBucket: 'resume-builder-6ad54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhG5sEj7zPnak4ADzP_jFlboYbNTQKdQo',
    appId: '1:599045906068:ios:c44c59dabeb528f3121e81',
    messagingSenderId: '599045906068',
    projectId: 'resume-builder-6ad54',
    storageBucket: 'resume-builder-6ad54.appspot.com',
    iosClientId:
        '599045906068-7mfom2apef9ok03lc1nvejb93h5u7spv.apps.googleusercontent.com',
    iosBundleId: 'com.buildmyresume.resumeBuilder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhG5sEj7zPnak4ADzP_jFlboYbNTQKdQo',
    appId: '1:599045906068:ios:c44c59dabeb528f3121e81',
    messagingSenderId: '599045906068',
    projectId: 'resume-builder-6ad54',
    storageBucket: 'resume-builder-6ad54.appspot.com',
    iosClientId:
        '599045906068-7mfom2apef9ok03lc1nvejb93h5u7spv.apps.googleusercontent.com',
    iosBundleId: 'com.buildmyresume.resumeBuilder',
  );

  static const FirebaseOptions defaultOption = FirebaseOptions(
    apiKey: 'AIzaSyBhG5sEj7zPnak4ADzP_jFlboYbNTQKdQo',
    appId: '1:599045906068:ios:c44c59dabeb528f3121e81',
    messagingSenderId: '599045906068',
    projectId: 'resume-builder-6ad54',
  );
}
